--- #YAML:1.0
name:                BS2000-LMS
version:             0.07
abstract:            Perl extension for library access under BS2000
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.36
distribution_type:   module
requires:     
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Thomas Dorner <dorner (AT) pause.org>
